thresholds:
  cpu_usage: 5      # CPU usage threshold in percentage
  memory_usage: 70   # Memory usage threshold in percentage
  disk_io: 100000       # Disk I/O threshold in MB/s
interval: 5         # Monitoring interval in seconds
